a) Write an IF-THEN rule derived from this decision tree, that can be used to classify 
instances in the data suppose your desire is to predict “yes” for the output variable. 

IF refund="no" AND income_above_80k="yes" AND (marital_status="single" OR marital_status="divorced") THEN cheat="yes"

b) In code, create a function with an if-else statement to implement the rule you wrote above 
in question 1a. You can name the function predict. The function takes the input data and 
returns a vector of predicted output values. You can decide if you want your function’s 
input data argument to be a numpy array or a data frame, ,then structure your function 
body to process the input data accordingly. Provide some brief document of your 
function. You can loop through each instance in the input data and assess whether the 
instance satisfies the rule for predicting “yes” or not. If the instance satisfies the rule for 
predicting “yes”, then predict 1, otherwise, predict 0. 

In [1]:
import numpy as np
import pandas as pd
import math

In [2]:


def predict(data): 
    counter=0
    pred_array = np.zeros(shape=(len(data),1))
    for i in data:
        if (i[0]=="no" and i[2]=="yes") and i[1] != "married":
            pred_array[counter]=1
        else:
            pred_array[counter]=0
        counter+=1
    return(pred_array)

    


c)Create another function that implements the rule for predicting “yes” for the output, but this time, you will not use if-else statement or a loop. Rather use numpy arrays, matrices or vector to vectorize your code for faster and more efficient implementation. If the instance satisfies the rule for predicting “yes”, then predict 1, otherwise, predict 0. You can use logical operators for such implementation to compare values of test instances to values of attributes in the rule. This function still takes the input data and returns a vector of predicted values. You can call this function vectorized_predict. 

In [3]:


def vectorized_predict (data):
    data.loc[((data['refund'] == 'no')&(data['income_above_80k']=='yes')
               & (data['marital_status']!='married')),'predict']=1
    predict_vector = data['predict'].to_numpy()
    return(predict_vector)
    


d)	Select the input data (refund, marital_status, income_above_80k) in the training data and apply your predict function to the input data to predict the outcome values of the input data. Your function should return a vector of predicted values. 

In [4]:

cheat_array =np.array([['yes','single','yes'],['no','married','yes'],['no','single','no'],
              ['yes','married','yes' ],['no','divorced','yes'],['no','divorced','yes'],
              ['yes','divorced','yes'],['no','single','yes'],['no',
            'married','no'],['no','single','yes']])

cheat_frame = pd.DataFrame(cheat_array, columns = ['refund','marital_status',
                                          'income_above_80k'])
cheat_frame['cheat']=[0,0,0,0,1,0,0,1,0,1]
cheat_frame['predict']=0

predict(cheat_array)


array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.]])

e)	Select the input data (refund, marital_status, income_above_80k) in the training data and apply your vectorized_predict function to the input data to predict the outcome values of the input data. Your function should return a vector of predicted values. Are the predicted values with the vectorized_predict function the same as the predicted values obtained through the predict function? (you should have the same results). 

In [5]:
vectorized_predict (cheat_frame)

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

f)	Include the predicted values as a column to the training data and name that column predicted_cheat. 

In [6]:
cheat_frame.rename(columns={"predict": "predicted_cheat"},inplace=True)

g)	Create a function that computes the overall accuracy of the classification. You can call this function overall_accuracy. The function should take two arguments, a vector of  actual output values and a vector of predicted output values, then returns the classification accuracy. Inside the function, you can use boolean logic to compare the actual and predicted values, then count the proportion of how many predicted values are equal to the actual values to get the overall accuracy. 

In [7]:
def overall_accuracy(col1,col2):
    a_compare = (col1==col2)
    return((np.count_nonzero(a_compare== True))/(a_compare.size))


overall_accuracy(cheat_frame['cheat'].to_numpy(),
                 cheat_frame['predicted_cheat'].to_numpy())


0.9

h)	Create a confusion matrix using the predicted and actual output values. You can use pandas crosstab function. 

In [8]:
pd.crosstab(cheat_frame['cheat'], cheat_frame['predicted_cheat'])

predicted_cheat  0  1
cheat                
0                6  1
1                0  3

i) Apply the vectorized_predict function to the input of the test dataset to predict the output values for the test dataset. Include these predicted values as a column to the test dataset and called this column predicted_cheat. 

In [9]:
test_array =np.array([['no','single','yes'],['no','single', 'yes'],['no','married','yes'],
              ['no','divorced','no'],['no','married','yes'],['no','single','yes'],
              ['yes','single','yes'],['no','single','yes'],['yes','married','yes'],
                                                          ['yes','single','no']])
test_frame = pd.DataFrame(test_array, columns = ['refund','marital_status',
                                          'income_above_80k'])
test_frame['cheat']=[0,0,0,0,0,0,0,1,1,1]
test_frame['predict']=0

test_frame['predict']=vectorized_predict (test_frame)
test_frame.rename(columns={"predict": "predicted_cheat"},inplace=True)
test_frame

refund marital_status income_above_80k  cheat  predicted_cheat
0     no         single              yes      0                1
1     no         single              yes      0                1
2     no        married              yes      0                0
3     no       divorced               no      0                0
4     no        married              yes      0                0
5     no         single              yes      0                1
6    yes         single              yes      0                0
7     no         single              yes      1                1
8    yes        married              yes      1                0
9    yes         single               no      1                0

j)	Apply the overall_accuracy function to the predicted out values and actual output values of the test set to compute the overall accuracy. Compare the overall accuracy of the test set and that of the training set. Is there overfitting? Why or why not? If there is overfitting, what would you do to avoid overfitting the rule to the training set? 

In [10]:
overall_accuracy(test_frame['cheat'].to_numpy(),
                 test_frame['predicted_cheat'].to_numpy())

0.5

There seems to be overfitting, as the accuracy dropped from .9 for the training set to .5 for the 
test set.  To mitigate the overfitting we could try to retrain the model using a simpler rule with fewer provisos.

a) Given the training dataset in question 1, write a function that computes the entropy of 
output variable. The function should take the entire training dataset, and the name of the 
output variable as arguments and return the entropy value. You can call the function, 
entropy. 
Note that entropy H(S) of the target variable T with possible values 𝐶𝑖 for a set of S 
examples is given by:
H(S) =  ― ∑𝑐
𝑖= 1𝑝𝑖log2 𝑝𝑖 
where 𝑝𝑖 𝑖𝑠 𝑝𝑟𝑜𝑝𝑜𝑟𝑡𝑖𝑜𝑛 𝑜𝑓 𝑐𝑙𝑎𝑠𝑠 𝑐𝑖 𝑖𝑛 𝑡ℎ𝑒 𝑆 𝑒𝑥𝑎𝑚𝑝𝑙𝑒𝑠 
Alternatively, you could also define entropy for a binary target variable as:
Where p = proportion of the desired class or proportion of “yes” in the given data. 
Apply the entropy function to the training dataset to compute the entropy. Do you think 
the data is more pure, less pure or more/less pure?

In [11]:
def entropy(data,var):
    p=(data[var].value_counts()[0])/(len(data[var]))
    l=math.log(p, 2.0)
    l2=math.log(1-p, 2.0)
    return -p*l-(1-p)*l2

entropy(cheat_frame,'cheat')

0.8812908992306927

This data is quite impure, as the entropy value is close to one.

b) Create another function that takes the dataset, the name of the output variable, and a 
specific input variable as arguments and returns the information gain for a split of the 
data on that specific input variable. You can call the function, information_gain. 
Information gain is defined as:
Apply the information_gain function to each input variable to compute the information 
gain for each input variable. Which input variables is the best (has the highest 
information gain) for creating one-rule? 

In [21]:
ent=entropy(cheat_frame,'cheat')

def information_gain(invar,outvar):
    ent1 = 0
    ent2 = 0
    ent3 = 0
    ig = 0
    
    df1= cheat_frame[invar ==invar.unique()[0]]
    port1 = len(df1.groupby(by="cheat", dropna=False).sum())
    if port1!=1:
        ent1=entropy(df1,'cheat')
        
    df2 = cheat_frame[invar ==invar.unique()[1]]
    port2 = len(df2.groupby(by="cheat", dropna=False).sum())
    if port2!=1:
        ent2=entropy(df2,'cheat')
        weight = (ent1)*(len(df1)/len(cheat_frame))+(ent2)*(len(df2)/len(cheat_frame))
        ig = ent-weight
        
    if len(cheat_frame.groupby(by=invar, dropna=False).sum())==3:
        df3= cheat_frame[invar ==invar.unique()[2]]
        port3 = len(df3.groupby(by="cheat", dropna=False).sum())
        if port3!=1:
            ent3=entropy(df3,'cheat')
            weight2 = (ent1)*(len(df1)/len(cheat_frame))+(ent2)*(len(df2)/len(cheat_frame))+(ent3)*(len(df3)/len(cheat_frame))
            ig = ent-weight2
    
    return ig
    
    
information_gain(cheat_frame['refund'],cheat_frame['cheat'])


0.19163120400671663

In [13]:
information_gain(cheat_frame['marital_status'],cheat_frame['cheat'])

0.2058021490143458

In [14]:
information_gain(cheat_frame['income_above_80k'],cheat_frame['cheat'])


0

For this dataset, the attribute: "marital_status" has the highest information gain ( approx. .21) relative to the output variable "cheat".  For this set, it is the best predictor.

Do a cross tabulation using the best attribute obtained in 2b above and the output variable 
in the training dataset. 


In [15]:
pd.crosstab(cheat_frame['marital_status'], cheat_frame['cheat'])

cheat           0  1
marital_status      
divorced        2  1
married         3  0
single          2  2


f)	Using the antecedent of your rule, extract the data covered by the rule and compute the coverage of the rule. 
 
coverage=(4 single instances/10 total instances) = .4


g)	Using the antecedent and precedent of your rule, extract the data covered by the rule and compute the accuracy of the rule. 
 
Accuracy = (2 single status cheated)/(4 covered by antecedent) = .5


h)	Create a function that implents the rule as an if-else statement to predict the outcomes of any instance (a vector of values associated with the input variables for a specific individual). The function should be able to take one or more instances as an argument in the form of a dataframe or numpy arrary. 
Paste your code an output here


In [16]:
def married_predict(data): 
    counter=0
    mar_pred_array = np.zeros(shape=(len(data),1))
    for i in data:
        if  i[1] == "single":
            mar_pred_array[counter]=1
        else:
            mar_pred_array[counter]=0
        counter+=1
    return(mar_pred_array)

i)	Implemement the function on the training set and test set in question 1 to get the predicted outputs for the training set and test set.  



In [17]:
married_predict(cheat_array)

array([[1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.]])

In [18]:
married_predict(test_array)

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.]])

In [19]:
cheat_frame['married_predict'] = married_predict(cheat_array)
cheat_frame['married_predict']=cheat_frame.married_predict.astype('int64')
overall_accuracy(cheat_frame['cheat'].to_numpy(),
                 cheat_frame['married_predict'].to_numpy())



0.7

In [20]:
test_frame['married_predict'] = married_predict(test_array)
test_frame['married_predict']=test_frame.married_predict.astype('int64')
overall_accuracy(test_frame['cheat'].to_numpy(),
                 test_frame['married_predict'].to_numpy())

0.5

Again, it seems there was a degree of underfitting, as the accuracy decreased from .7 on the training set to .5 on the test set.  Additionally, since the model was generating a binary prediction, the accuracy on the test set of .5 means the model is hardly useful.